name: ci

on:
  pull_request:

concurrency:
  group: ci-${{ github.event.repository.name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
